# Generated by Django 6.0.7 on 2026-07-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=255)),
                ('auctionName', models.CharField(max_length=300)),
                ('auctionDate', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidderName', models.CharField(max_length=255)),
                ('companyName', models.CharField(blank=True, max_length=200)),
                ('winnerPhone', models.CharField(max_length=20)),
                ('winnerEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('winningAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cpoAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cpoBank', models.CharField(blank=True, max_length=100)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('initialPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='invoices.auction')),
            ],
        ),
    ]
