# Generated by Django 6.0.7 on 2026-07-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(max_length=50, unique=True)),
                ('invoiceDate', models.DateField()),
                ('feePercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dueDate', models.DateField()),
                ('status', models.CharField(choices=[('invoice_generated', 'Invoice Generated'), ('pending_payment', 'Pending Payment'), ('payment_submitted', 'Payment Submitted'), ('under_verification', 'Under Verification'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('waived', 'Waived')], default='invoice_generated', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.winner')),
            ],
        ),
    ]
