# Generated by Django 6.0.7 on 2026-07-30 12:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='feePercentage',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='winner',
            name='winnerEmail',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('filePath', models.FileField(upload_to='attachments/')),
                ('fileExtension', models.CharField(blank=True, max_length=10)),
                ('documentType', models.CharField(choices=[('bank_slip', 'Bank Slip'), ('transfer_proof', 'Transfer Proof'), ('cpo', 'CPO Document'), ('invoice', 'Invoice Document'), ('payment_confirmation', 'Payment Confirmation'), ('supporting_document', 'Supporting Document'), ('other', 'Other')], default='other', max_length=30)),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('fileSize', models.DecimalField(decimal_places=2, help_text='KB', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invoices.invoice')),
                ('uploadedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('userRole', models.CharField(blank=True, max_length=30)),
                ('previousValue', models.CharField(blank=True, max_length=100)),
                ('newValue', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('actionDate', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoices.invoice')),
                ('performedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.95'), max_digits=5)),
                ('configured_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('configured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('batchName', models.CharField(blank=True, max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('auctionDate', models.DateField()),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('totalRecords', models.IntegerField(default=0)),
                ('validRecords', models.IntegerField(default=0)),
                ('invalidRecords', models.IntegerField(default=0)),
                ('importedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='importBatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.importbatch'),
        ),
        migrations.AddField(
            model_name='winner',
            name='importBatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='invoices.importbatch'),
        ),
        migrations.CreateModel(
            name='InvoiceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotNumber', models.CharField(max_length=50)),
                ('auctionName', models.CharField(max_length=300)),
                ('initialPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('winningAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cpoAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cpoBank', models.CharField(blank=True, max_length=100)),
                ('feePercentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lotFee', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('submittedAt', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='invoices.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPaid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('paymentMethod', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('telebirr', 'Telebirr'), ('cpo', 'CPO'), ('other', 'Other')], max_length=20)),
                ('paymentDate', models.DateField()),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('verifiedDate', models.DateTimeField(blank=True, null=True)),
                ('paymentStatus', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('verifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('auction_manager', 'Auction Manager'), ('finance_manager', 'Finance Manager'), ('call_operator', 'CRM / Call Center Officer'), ('viewer', 'Viewer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
