# Generated by Django 6.0.7 on 2026-08-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_feepercentage_alter_invoice_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch',
            options={'verbose_name_plural': 'Import batches'},
        ),
        migrations.AddField(
            model_name='winner',
            name='bidderNameAmharic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
