# Generated by Django 6.0.7 on 2026-08-12 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_importbatch_options_winner_biddernameamharic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('periodLabel', models.CharField(blank=True, max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('rowCount', models.IntegerField(default=0)),
                ('totalAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('file', models.FileField(upload_to='reports/%Y/%m/')),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
                ('generatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
