# Generated by Django 6.0.7 on 2026-08-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_generatedreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='callNotes',
            field=models.TextField(blank=True, default='', help_text='Call Center follow-up note — single mutable field, not a history log.'),
        ),
    ]
